### ISSUE TITLE
API 9 issues

### ISSUE THREAD

**Issue by drejjmit** [Junie-774/CraftingList#23]
15:06:35.405 | DBG [CraftingList] Last food: 0
15:06:35.408 | DBG [CraftingList] [CraftHelper.ChangeJobs()] Changing jobs to Alchemist
15:06:35.417 | ERR Exception during raise of "Void <InvokeSafely>b__0()"
System.NullReferenceException: Object reference not set to an instance of an object.
   at CraftingList.Utility.ChatManager.SendMessageInternal(String message)
   at CraftingList.Utility.ChatManager.FrameworkUpdate(IFramework framework)
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\Utility\EventHandlerExtensions.cs:line 112

**Comment by drejjmit** [comment]
18:22:07.727 | INF [LOCALPLUGIN] Finished loading CraftingList.dll
--------------------------------
18:22:09.274 | ERR Exception during raise of "Void DrawUI()"
System.InvalidCastException: Unable to cast object of type 'Dalamud.Interface.Internal.TextureManagerTextureWrap' to type 'ImGuiScene.TextureWrap'.
   at CraftingList.UI.CraftingListTab.EntryListTable.DrawEntries(List`1 entries, String tableName)
   at CraftingList.UI.CraftingListTab.CraftingListTab.Draw()
   at CraftingList.PluginUI.DrawSettingsWindow()
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\Utility\EventHandlerExtensions.cs:line 112
--------------------------------

**Comment by drejjmit** [comment]
I tried v2.5.2, but it doesn't seem to know how to change job or how to repair anymore.
I also didn't get any Craft complete notification

**Comment by lyndistt** [comment]
> I tried v2.5.2, but it doesn't seem to know how to change job or how to repair anymore. I also didn't get any Craft complete notification

I'm also having the same issues. I've tried reinstalling and played around with the delays and timers

**Comment by drejjmit** [comment]
15:06:35.405 | DBG [CraftingList] Last food: 0
15:06:35.408 | DBG [CraftingList] [CraftHelper.ChangeJobs()] Changing jobs to Alchemist
15:06:35.417 | ERR Exception during raise of "Void <InvokeSafely>b__0()"
System.NullReferenceException: Object reference not set to an instance of an object.
   at CraftingList.Utility.ChatManager.SendMessageInternal(String message)
   at CraftingList.Utility.ChatManager.FrameworkUpdate(IFramework framework)
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\Utility\EventHandlerExtensions.cs:line 112

**Comment by Junie-774** [comment]
I believe these have been fixed, pending testing. Thanks for all the effort on this! I'll close this after a week (once I remember) if the latest update seems to work

**Comment by OtisOathkeeper** [comment]
Initial testing seems fine, repairs work, and macros roll. The repairall field may have been updated when SE added the left and right buttons to the category field in many windows across the game.

While this isn't an issue, clist would remember previously selected macros when selecting items, which made it way easier to set up a suite of items. After this new update, the macro field is always cleared. Do you think we could make it remember macros as it did before?

**Comment by Junie-774** [comment]
Yeah now that you mention it that is more convenient behavior. If someone needs a different macro then they're expecting to click that field anyway. I'll add that in the next update along with the usual patch fixes. API 9 seems to be working fine for now though so i'm closing this issue
