### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by YsEmei** [Junie-774/CraftingList#29]
Got this crash today. I think it was because i was out of Dark Matter and it couldn't repair and swapped job. Maybe the error log will help:
```
Unhandled native exception occurred at ffxiv_dx11.exe+1B2DCD4	(MemCpy:::MoveSmall1)
Code: C0000005

System Time: 2024-07-12 22:37:49.0089953

   at CraftingList.Crafting.CraftHelper.ExitCrafting()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at CraftingList.Crafting.CraftHelper.ExitCrafting()
   at CraftingList.Crafting.Crafter.<CraftAllItems>b__5_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at CraftingList.Crafting.Crafter.QuickSynthesizeEntry(CListEntry entry)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at CraftingList.Crafting.Crafter.PerformOneQuickSynth(CListEntry entry)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at CraftingList.Crafting.Crafter.WaitForQuickSynthToFinish(CListEntry entry, Int32 numToQuickSynth)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at CraftingList.Crafting.CraftHelper.Repair()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.DelayPromise.CompleteTimedOut()
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()


Exception Info #0
Address: C0000005
Flags: 0
Address: 7FF7865CDCD4
Parameters: 0, C0152FB2A2
Call Stack
{
  [0]	ffxiv_dx11.exe+1B2DCD4	(MemCpy:::MoveSmall1)
  [1]	ffxiv_dx11.exe+1B2DCD4	(MemCpy:::MoveSmall1)
  [2]	ffxiv_dx11.exe+5A500	(Client::System::String::Utf8String.Copy+0x30)
  [3]	ffxiv_dx11.exe+9016F3	(Client::UI::Shell::RaptureShellModule.ExecuteMacro+0x153)
  [4]	7FFA1208828B
  [5]	2ACF871D490
  [6]	C0154FDCD0
  [7]	26BDDA9A278
  [8]	1
  [9]	E7AD92D40F2E
  [10]	coreclr.dll+3FE9E8	(coreclr_shutdown+0x44228)
  [11]	C0154FDC00
}

Registers
{
  RAX:	2ACF871D7EA
  RBX:	2ACF871D7C8 [2ACF871D7EA]
  RCX:	2ACF871D7EA
  RDX:	C0152FB2A2
  R8:	1
  R9:	ffxiv_dx11.exe+1B2DCD4	(MemCpy:::MoveSmall1)
  R10:	ffxiv_dx11.exe+0	(_ImageBase)
  R11:	7FFA1208A458 [7FFA130C26F0]
  R12:	0
  R13:	0
  R14:	C0154FDCD0
  R15:	2AD502F3430
  RSI:	2ACF871D490 [ffxiv_dx11.exe+1F1A308	(vtbl_Client::UI::Shell::RaptureShellModule)]
  RDI:	C0154FDCD8 [C0152FB2A2]
  RBP:	C0154FDB70 [C0154FDC80]
  RSP:	C0154FDA68 [ffxiv_dx11.exe+5A500	(Client::System::String::Utf8String.Copy+0x30)]
  RIP:	ffxiv_dx11.exe+1B2DCD4	(MemCpy:::MoveSmall1)
}

Stack
{
  [RSP+0]	ffxiv_dx11.exe+5A500	(Client::System::String::Utf8String.Copy+0x30)
  [RSP+8]	26C3D723490 [7FFA0F55FDB0]
  [RSP+10]	F
  [RSP+18]	303A2F481EB2
  [RSP+20]	2AD971E16A0
  [RSP+28]	2ACF871D7C0
  [RSP+30]	ffxiv_dx11.exe+9016F3	(Client::UI::Shell::RaptureShellModule.ExecuteMacro+0x153)
  [RSP+38]	2ACF871D490 [ffxiv_dx11.exe+1F1A308	(vtbl_Client::UI::Shell::RaptureShellModule)]
  [RSP+40]	2AD502F3430
  [RSP+48]	C0154FDAF0 [E7AD92D40F2E]
  [RSP+50]	7FFA176DA56D [19C35D30C4834890]
  [RSP+58]	2AD971E16A0
  [RSP+60]	7FFA1208828B [453D83010C46C641]
  [RSP+68]	2ACF871D490 [ffxiv_dx11.exe+1F1A308	(vtbl_Client::UI::Shell::RaptureShellModule)]
  [RSP+70]	C0154FDCD0
  [RSP+78]	26BDDA9A278 [7FFA12296818]
}
```
```
2024-07-13 00:37:24.507 +02:00 [DBG] [CraftingList] [WaitForAddon] Waiting for addon 'SynthesisSimple' to close.
2024-07-13 00:37:27.451 +02:00 [DBG] [InventoryTools] Craft completed
2024-07-13 00:37:28.700 +02:00 [DBG] [CraftingList] [WaitForAddon] Wait completed for 'SynthesisSimple'
2024-07-13 00:37:36.228 +02:00 [DBG] [CraftingList] [CraftHelper.ExitCrafting()] Closing Recipe Note...
2024-07-13 00:37:36.229 +02:00 [DBG] [CraftingList] [WaitForAddon] Waiting for addon 'RecipeNote' to close.
2024-07-13 00:37:36.407 +02:00 [DBG] [CraftingList] [WaitForAddon] Wait completed for 'RecipeNote'
2024-07-13 00:37:40.060 +02:00 [DBG] [CraftingList] [CraftHelper.Repair()] Repairing...
2024-07-13 00:37:40.060 +02:00 [DBG] [CraftingList] [WaitForAddon] Waiting for addon 'Repair'.
2024-07-13 00:37:40.155 +02:00 [DBG] [CraftingList] [WaitForAddon] Waiting done!
2024-07-13 00:37:42.656 +02:00 [DBG] [CraftingList] [CraftHelper.Repair()] Clicking repair all...
2024-07-13 00:37:42.657 +02:00 [DBG] [CraftingList] [WaitForAddon] Waiting for addon 'SelectYesno'.
2024-07-13 00:37:47.779 +02:00 [ERR] [CraftingList] Addon SelectYesno timed out
2024-07-13 00:37:47.779 +02:00 [DBG] [CraftingList] [WaitForAddon] Waiting for addon 'SelectYesno' to open timed out.
2024-07-13 00:37:47.779 +02:00 [DBG] [CraftingList] [CraftHelper.ExitCrafting()] Closing Recipe Note...
```

**Comment by drejjmit** [comment]
Still crashes every now and then with latest version
```
Unhandled native exception occurred at ffxiv_dx11.exe+1CC50F2	(GFSDK_SSAO_CreateContext_D3D11+0x197FA2)
Code: C0000005
System Time: 2024-08-08 15:01:47.8499893

   at SimpleTweaksPlugin.Tweaks.UiAdjustment.KeepOpen.HideDetour(AtkUnitBase* atkUnitBase, Byte a2, Byte a3, Int32 a4)
   at CraftingList.SeFunctions.PtrRecipeNote.Close()
   at CraftingList.Crafting.CraftHelper.ExitCrafting()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at CraftingList.Crafting.CraftHelper.ExitCrafting()
   at CraftingList.Crafting.Crafter.<CraftAllItems>b__5_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at CraftingList.Crafting.Crafter.QuickSynthesizeEntry(CListEntry entry)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at CraftingList.Crafting.Crafter.PerformOneQuickSynth(CListEntry entry)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at CraftingList.Crafting.Crafter.WaitForQuickSynthToFinish(CListEntry entry, Int32 numToQuickSynth)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.DelayPromise.CompleteTimedOut()
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by Junie-774** [comment]
Yeah, i'm really not sure whats going on or how to fix it
